default['ruby']['user']    = 'vagrant'
default['ruby']['group']   = 'vagrant'
default['ruby']['version']   = '2.1.0'
default['ruby']['rbenv_url']   = 'https://github.com/sstephenson/rbenv.git'
default['ruby']['ruby_build_url']   = 'https://github.com/sstephenson/ruby-build.git'
